### ISSUE TITLE
Package linked to folder causing Payment Required error

### ISSUE THREAD

**Issue by BenRacicot** [tjunnone/npm-check-updates#510]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

I LOVE NCU... Just thought I'd mention...
My partner and I merged our repos and stopped using an NPM hosted package. The package now links to a folder.

However, `"@recruitler/common": "file:../common"` in my package.json file is causing an error when I run `ncu`.

Here is the error:
```
Unhandled rejection HTTPError: Response code 402 (Payment Required)
    at EventEmitter.emitter.on (/usr/local/lib/node_modules/npm-check-updates/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

* node version: v10.8.0
* npm version: 6.4.1
* npm-check-updates version: 3.0.8

---------------------------

**Comment by stoically** [comment]
This is fixed in master through #508 and will be available with the next release.

**Comment by raineorshine** [comment]
Fixed as of v3.0.9!

**Comment by peterkrieg** [comment]
I'm still seeing this behavior in version `3.1.9` in `ncu`.  I had private npm packages in my `package.json`  which were for a stagnant account with no payment.  So definitely an edge case but just though I would mention it 🙂

**Comment by stoically** [comment]
This issue was about `file:` dependencies which were wrongly checked against the registry - is that the case for you? Otherwise you might want to open a new issue.

Also, maybe give `3.1.20` a shot.
